### ISSUE TITLE
Firefox installer

### ISSUE THREAD

**Issue by eyedeekay** [eyedeekay/firefox.profile.i2p#2]
The Windows version should install a suitable Firefox version, and optionally the Linux script should probably assist with this too. I don't have any idea if it's possible on OSX.

https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/StubArch.html appears to be an important point of reference.

**Comment by zlatinb** [comment]
(Moving the discussion from Reddit here)

Mozilla has some rules about redistributing Firefox https://www.mozilla.org/en-US/foundation/trademarks/distribution-policy/ and I think we are mostly ok, because we do not modify Firefox in any way.  Although there are two bits which are open to interpretation:

1. "You may not modify the installation process of Firefox or use it to install any other themes, plugins, extensions, or software." - on one hand we're not touching the installation process of the full installer, but on the other we are writing our own stub installer
2. "You may not add to, remove, or change any part of Firefox, including the Mozilla trademarks themselves. For example, you may not add any extensions to Firefox." - this is fuzzy in our case because we are adding NoScript and HTTPS  Everywhere

Anyway, I've sent them an email explaining our intentions and hopefully they'll be ok.

Other than that, I spent a few hours staring at the stub code, and most of it we don't need. The parts that we do like 32/64 bit detection can be copy-pasted. The URL of the download "bouncer" is there in plain sight; I tried hitting it manually and downloading from the Mozilla servers worked :)

One complicated bit is the locale selection, but let's leave that for future work. For now, assume every time you see the ${AB_CD} variable its value will be "en-US"

That leaves us with the uninstaller; we'll end up generating two uninstallers - one for firefox itself and one for the profile. Not ideal, but let's not worry about it right now.

**Comment by zlatinb** [comment]
Scratch the bundling of Firefox, Mozilla got back to me and they are not happy with the idea.

**Comment by eyedeekay** [comment]
I can live with that, TBH. Closing this one.
